apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  storageClassName: aks-azurefile
  volumeName: azurefile
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
