apiVersion: v1
kind: Pod
metadata:
  name: mysql-config-pod
  labels:
    name: mysql-config-pod
spec:
  containers:
  - name: mysql-config-pod-container
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Hostname: ${host}"; echo "User: ${user}"; echo "Database: ${database}"; sleep 10; done']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
    envFrom:
    - configMapRef:
        name: mysql-config
