apiVersion: v1
kind: Pod
metadata:
  name: mysql-secret-pod
  labels:
    name: mysql-secret-pod
spec:
  containers:
  - name: mysql-secret-pod
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Password: ${PASSWORD}"; sleep 10; done']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env: 
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: mysql-password
