apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
spec:
  provider: azure
  secretObjects:
    - data: 
      - key: MYSQL_PASSWORD
        objectName: MYSQL_PASSWORD
      secretName: mysql-password
      type:  Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: mysqlsecretsaks
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: mysql-password
          objectType: secret
          objectAlias: MYSQL_PASSWORD
          objectVersion: ""
    tenantId: 4637d11f-57b9-4266-ae59-6700ed3071f2