apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
  namespace: hml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-hml
subjects: 
  - kind: ServiceAccount
    name: sysadmin
    namespace: hml